title: Moonlit Door
description: Software
theme: jekyll-theme-architect
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
permalink: /:categories/:year/:month/:day/:slug
collections:
  customPages:
    output: true
include:
  - README.md
