title: Moonlit Door Software
description: A short description of your site's purpose
theme: jekyll-theme-architect
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
