title: Moonlit Door Software
description: Test5
theme: jekyll-theme-architect
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
collections:
  customPages:
    output: true
    permalink: /:name
  definitions:
    output: true
    permalink: /definition/:name
include:
  - README.md
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
