title: Moonlit Door Software
description: Test
theme: jekyll-theme-architect
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
collections:
  customPages:
    output: true
    permalink: /:name
include:
  - README.md
