title: Moonlit Door
description: Helping You Deliver Better Software.
theme: jekyll-theme-architect
google_analytics: UA-68156775-4
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
collections:
  customPages:
    output: true
    permalink: /:name
  definitions:
    output: true
    permalink: /definition/:name
  drafts:
    output: true
    permalink: /:name
include:
  - README.md
markdown: kramdown
